name: Code Review & Quality Checks

on:
  pull_request:
    branches:
      - main
      - dev
      - feature/*

permissions:
  contents: read
  security-events: write   # needed for CodeQL
  pull-requests: write     # so tools can comment on PRs

jobs:
  lint:
    name: Lint with ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: |
          npx eslint . || exit 1

  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: |
          npm audit --audit-level=moderate || echo "Security warnings found (non-blocking)"
        continue-on-error: true

  codeql:
    name: CodeQL Security Scan
    runs-on: ubuntu-latest
    needs: [lint, audit]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript

      - name: Build project (optional)
        run: npm install

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
